name: Docker Image CI

on:
  push:
    branches:
      - main  # 你可以根据需要修改为其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Alibaba Cloud Container Registry
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: echo $ACR_PASSWORD | docker login registry.cn-heyuan.aliyuncs.com -u $ACR_USERNAME --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t registry.cn-heyuan.aliyuncs.com/chang_kong/hello-github:v1.0.0 .
        docker push registry.cn-heyuan.aliyuncs.com/chang_kong/hello-github:v1.0.0